### ISSUE TITLE
Android Error Validation failed for operation STRIDED_SLICE

### ISSUE THREAD

**Issue by Wangyang9957** [natmlx/movenet-multipose-unity#1]
HI,The following error was encountered on Android：
NN_RET_CHECK failed (frameworks/ml/nn/common/operations/StridedSlice.cpp:109): inputType == OperandType::TENSOR_FLOAT16 || inputType == OperandType::TENSOR_FLOAT32 || inputType == OperandType::TENSOR_QUANT8_ASYMM || inputType == OperandType::TENSOR_QUANT8_ASYMM_SIGNED Unsupported input operand type for STRIDED_SLICE op: TENSOR_INT32

Validation failed for operation STRIDED_SLICE

**Comment by olokobayusuf** [comment]
Hey @Wangyang9957 , can you try setting the `computeTarget` to `CPUOnly` before calling `Deserialize`?
```csharp
var modelData = await MLModelData.FromHub(...);
modelData.computeTarget = MLModelData.ComputeTarget.CPUOnly; // <-- add this line
var model = modelData.Deserialize();
```
Let me know if the issue persists.

**Comment by olokobayusuf** [comment]
This has been reproduced and fixed upstream.

**Comment by Wangyang9957** [comment]
Sorry for the late reply.  it can be used normally。Thank you 。

**Comment by olokobayusuf** [comment]
Perfect!
